### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by roozbehp** [slashmili/python-jalali#148] opened 2024-03-20 12:40 UTC
It appear that the conversion code is copied from http://www.farsiweb.info/jalali/jalali.c without following its license and mentioning its copyright holders (which includes myself). Would you please fix it at your earliest opportunity? The license should be LGPL 2.1 or later and the copyright holders should be Roozbeh Pournader and Mohammad Toossi, as well as any new contributors.

**Comment by farzadghanei** [comment] 2024-03-20 12:58
@slashmili I had the impression the conversion code is based on what's commented in the `jalali` module:
```
# dervied from http://farsitools.sf.net
# Copyright (C) 2003-2011  Parspooyesh Fanavar (http://parspooyesh.com/)
```
https://github.com/slashmili/python-jalali/blob/main/jdatetime/jalali.py#L1

But I agree, the logic seems very much the same to what @roozbehp is sharing, and I can confirm is the algorithm implemented and distributed by Roozbeh Pournader in C.

Although what `jdatetime` uses is a re-implementation in Python and not the same exact code, the logic is almost identical.

@roozbehp since this library is a re-implementation, and it's being distributed under a different yet still liberal and open license ([Python license](https://docs.python.org/3/license.html)), could you please share your opinion regarding this license difference?

**Comment by roozbehp** [comment] 2024-03-20 13:24
The Python implementation in jalali.py is clearly a derived work from my work, and as such, should carry the name of the copyright holders and be distributed under LGPL 2.1 or later. It doesn't matter that it's not the same exact C code. It's clearly derived from that code, and even the names of most variables is the same.

BTW, farsitools.sf.net, which is mentioned at the top of that file, is where a copy of my original C code used to live. It was maintained by the FarsiWeb Project Group. So the file header admits it's being derived from our work, it just drops the copyright holders' names and changes the license without permission.

If there are reasons LGPL cannot be used, please tell me the reasons so I may consider relicensing. (You would still need to hunt down the other copyright holder, Mohammad Toossi.)

**Comment by roozbehp** [comment] 2024-03-20 13:31
Looking at https://pypi.org/search/?c=License+%3A%3A+OSI+Approved+%3A%3A+GNU+Library+or+Lesser+General+Public+License+%28LGPL%29, it appears that a lot of Python modules there are licensed under LGPL, so I don't see a reason this can't be fixed to LGPL.

**Comment by slashmili** [comment] 2024-03-20 14:59
@roozbehp I sincerely apologize for the oversight. It was a mistake on my part and should not have occurred.

I've updated the Jalali file and merge it to main.

About the license of the `python-jalali` project, I need to conduct some research on my options as I prefer to keep it under the Python License.

**Comment by farzadghanei** [comment] 2024-03-20 15:12
> Looking at https://pypi.org/search/?c=License+%3A%3A+OSI+Approved+%3A%3A+GNU+Library+or+Lesser+General+Public+License+%28LGPL%29, it appears that a lot of Python modules there are licensed under LGPL, so I don't see a reason this can't be fixed to LGPL.

@roozbehp this Jalali date time library is trying to mimic the API of [datetime](https://docs.python.org/3/library/datetime.html) module in the Python standard library (as much as possible for generic use cases), and to be a drop-in replacement (with caveats).

I think that's why the license was chosen to be what Python uses, so it can be safely used everywhere, the Python standard library can be used. Changing it to LGPL, may have some consequence, hence my question, if there would be a way to keep the license as is for the module (adding attributions in the module is not an issue and already done by #149 ).

More info on Python license (currently used by this library):
 - FSF approved license, [GPL compatible](https://web.archive.org/web/20211227002639/https://www.gnu.org/licenses/license-list.html#Python)
 - [ OSI approved](https://opensource.org/license/python-2-0)

**Comment by slashmili** [comment] 2024-03-20 15:43
alternatively we can release `jalali.py` under a separate package and just use it as a dependency.Do you think this is an acceptable solution?

**Comment by farzadghanei** [comment] 2024-03-20 16:48
If I'm not mistaken, it should be OK to vendor the LGPL file in packages with other licenses, as long as that specific module is licensed LGPL, the rest of the package can keep a different license.

There are other examples of this (old versions of [requests](https://github.com/psf/requests/issues/3389#issuecomment-231179332), etc.)

I may be missing something, but I don't see much difference between this, or extracting that module and distributing that as LGPL (which I agree that is still an option).
 
Maybe it's possible to
 - keep the `jalali.py` module, and distribute it as LGPL (as it should), including all future changes.
 - ensure that it's properly reference the LGPL module in the project's documentation and the fact that parts of the code are licensed differently. maybe include something like the following in the license/readme files:

```
This project is licensed under the Python license, with the exception of the `jalali.py` module, which is included under the terms of the LGPL. The source code and its license can be found at `jalali.py`. 
```

This is just an example BTW.

**Comment by roozbehp** [comment] 2024-03-21 01:32
Separating jalali.py to a dependency package is fine with me, as well as including it in the same package and clarifying that the package includes code under two different licenses. In the second case, you need to be careful about the metadata, so users would know that they are using LGPL code too and be aware of its requirements.

**Comment by roozbehp** [comment] 2024-03-23 18:53
Would you create a pull request for https://github.com/slashmili/python-jalali/blob/main/LICENSE too?

**Comment by slashmili** [comment] 2024-03-25 09:51
@roozbehp done in #150

Just for sake of transparency:

* I already extracted the jalali.py into [jalali-core](https://github.com/slashmili/jalali-core) which will be released under LGPL.
* I'm planning to remove the LGPL code from this repo and then remove all the LGPL licence and references form this repo.

**Comment by slashmili** [comment] 2024-03-26 09:42
As all issues been addressed

**Closed by slashmili** 2024-03-26 09:42 UTC

**Comment by slashmili** [comment] 2024-04-03 17:58
FYI @roozbehp it seems to me that these repos are using the same algorithm

https://github.com/jalaali

**Comment by roozbehp** [comment] 2024-04-04 01:27
> FYI @roozbehp it seems to me that these repos are using the same algorithm
> 
> https://github.com/jalaali

Thanks a lot. I took a quick look, and at least the JavaScript, Python, and Go versions appear to be independently developed and use a different algorithm too. Would you please point me to a file where you think could have a copyright issue?

**Comment by slashmili** [comment] 2024-04-05 01:40
Sorry for the false alarm, I was looking at the python code and saw some similar calculations.
